# Configurações da Fonte de Dados (H2 em memória)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console do H2 (útil para debug se você pausar o teste)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# 'create-drop' garante que o esquema seja criado no início e excluído ao fim dos testes
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true